"""Initial commit.

Revision ID: 920594c4ff57
Revises: 
Create Date: 2025-02-13 16:27:27.810390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920594c4ff57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(length=45), nullable=False),
    sa.Column('suburb', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('state', sa.String(length=45), nullable=False),
    sa.Column('postal_code', sa.String(length=4), nullable=False),
    sa.Column('country', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Enum('billing_address', 'postal_address', 'shipping_address', 'office_address'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractor_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('postal_address_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('abn', sa.String(length=11), nullable=True),
    sa.Column('accounts_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('discipline', sa.String(length=255), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['postal_address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_contact_id', sa.Integer(), nullable=False),
    sa.Column('secondary_contact_id', sa.Integer(), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['secondary_contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('secretary', 'director', 'building_designer', 'draftsperson', 'junior_draftsperson', name='role_enum'), nullable=False),
    sa.Column('employment_status', sa.Enum('full_time', 'part_time', 'casual', 'not_employed', name='employment_status_enum'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('lead', 'job', 'completed', 'no_sale', name='status_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initial_inquiry_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('storeys', sa.Integer(), nullable=True),
    sa.Column('referral_source', sa.Enum('google', 'referral', 'repeat_client', 'jkc', 'smce', 'word_of_mouth', 'website', name='referral_source_enum'), nullable=True),
    sa.Column('payment_basis', sa.Enum('lump_sum', 'hourly_rate', name='payment_basis_enum'), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('asset', 'liability', name='type_enum'), nullable=False),
    sa.Column('status', sa.Enum('not_invoiced', 'invoiced', 'paid', 'partially_invoiced', name='status_enum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('estimate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('actual', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('lead', 'information_request', name='type_enum'), nullable=False),
    sa.Column('status', sa.Enum('follow_up', 'resolved', 'in_progress', name='status_enum'), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('comment', 'reminder', 'follow_up', name='type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_has_contractor',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('contractor_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['contractor_type_id'], ['contractor_type.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'contractor_id')
    )
    op.create_table('project_is_building_class',
    sa.Column('building_class_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_class_id'], ['building_class.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('building_class_id', 'project_id')
    )
    op.create_table('staff_project',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'project_id')
    )
    op.create_table('staff_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_time')
    op.drop_table('staff_project')
    op.drop_table('project_is_building_class')
    op.drop_table('project_has_contractor')
    op.drop_table('note')
    op.drop_table('call_log')
    op.drop_table('budget')
    op.drop_table('project')
    op.drop_table('staff')
    op.drop_table('contractor')
    op.drop_table('client')
    op.drop_table('contact')
    op.drop_table('contractor_type')
    op.drop_table('building_class')
    op.drop_table('address')
    # ### end Alembic commands ###
