"""Add project number to projects

Revision ID: c3754ec8e950
Revises: 7e4982ea5c93
Create Date: 2025-02-11 10:35:05.667658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3754ec8e950'
down_revision: Union[str, None] = '7e4982ea5c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'project', ['project_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'project_number')
    # ### end Alembic commands ###
